import React, { useState, useEffect, useRef, Component } from "react";
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, Legend } from "recharts";
import * as XLSX from 'xlsx';

class ErrorBoundary extends Component {
  constructor(p){super(p);this.state={err:null}}
  static getDerivedStateFromError(e){return{err:e}}
  render(){if(this.state.err)return <div style={{padding:'2rem',textAlign:'center'}}><h2>Napaka</h2><p>{this.state.err?.message}</p><button onClick={()=>{this.setState({err:null});window.location.reload()}} style={{padding:'8px 16px',background:'#2563eb',color:'#fff',border:'none',borderRadius:6,cursor:'pointer'}}>Ponovno naloži</button></div>;return this.props.children}
}
function simpleHash(s){let h=0;for(let i=0;i<s.length;i++){h=((h<<5)-h)+s.charCodeAt(i);h=h&h}return Math.abs(h).toString(36)+s.length.toString(36)}
async function hashPwd(p,salt){if(typeof crypto!=='undefined'&&crypto.subtle){const d=new TextEncoder().encode(salt+p);const b=await crypto.subtle.digest('SHA-256',d);return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}return simpleHash(salt+p+salt)}
const MS_FULL=["Januar","Februar","Marec","April","Maj","Junij","Julij","Avgust","September","Oktober","November","December"];
const MS_SHORT=["Jan","Feb","Mar","Apr","Maj","Jun","Jul","Avg","Sep","Okt","Nov","Dec"];
const COLORS=["#2563eb","#0d9488","#d97706","#dc2626","#7c3aed","#059669","#e11d48","#0284c7","#ca8a04","#6366f1","#be185d","#15803d","#ea580c","#4f46e5","#0891b2","#a21caf","#65a30d"];
const CATS=[
  {id:"housing",name:"Stanovanjski stroški",type:"fixed",subs:[{id:"rent",name:"Najemnina ali obrok hipotekarnega kredita",dp:710},{id:"utilities",name:"Položnice (elektrika, voda, ogrevanje, smeti, komunalne storitve)",dp:250},{id:"admin",name:"Stroški upravnika",dp:0},{id:"internet",name:"Internet, TV in telefonija (paket)",dp:70},{id:"propIns",name:"Zavarovanje nepremičnine",dp:0}]},
  {id:"transport_fix",name:"Prevoz (fiksni)",type:"fixed",subs:[{id:"carLoan",name:"Obrok za avtomobilski kredit/leasing",dp:0},{id:"carIns",name:"Avtomobilsko zavarovanje (obvezno in kasko)",dp:0}]},
  {id:"children_fix",name:"Otroški stroški (fiksni del)",type:"fixed",subs:[{id:"kindergarten",name:"Vrtčevski prispevki",dp:640}]},
  {id:"debts",name:"Dolgovi",type:"fixed",subs:[{id:"consLoans",name:"Obroki za potrošniške kredite",dp:0}]},
  {id:"savings",name:"Varčevanje in naložbe",type:"fixed",subs:[{id:"vacSav",name:"Redno mesečno varčevanje za dopust (9x)",dp:300},{id:"etf",name:"Mesečno ETF",dp:200},{id:"tradeRep",name:"Mesečno Trade Republic",dp:700}]},
  {id:"food",name:"Hrana",type:"var",subs:[{id:"groceries",name:"Nakup živil",dp:650},{id:"eatOut",name:"Prehranjevanje zunaj (restavracije, kavarne, dostava hrane)",dp:0},{id:"snacks",name:"Malice in prigrizki na poti",dp:20}]},
  {id:"transport_var",name:"Prevoz (variabilni del)",type:"var",subs:[{id:"fuel",name:"Gorivo",dp:60},{id:"parking",name:"Parkirnine, cestnine",dp:5},{id:"carMaint",name:"Vzdrževanje in popravila avtomobila",dp:0},{id:"taxi",name:"Taxi, ride sharing",dp:5}]},
  {id:"clothing",name:"Oblačila in osebna nega",type:"var",subs:[{id:"clothes",name:"Nakup oblačil",dp:50},{id:"shoes",name:"Nakup obutve",dp:50},{id:"hair",name:"Frizerske storitve",dp:50},{id:"depil",name:"Depilacija",dp:0},{id:"drug",name:"Drogerija",dp:50}]},
  {id:"fun",name:"Zabava in prosti čas",type:"var",subs:[{id:"hobbies",name:"Hobiji in prostočasne dejavnosti",dp:0},{id:"trips",name:"Izleti, potovanja",dp:0},{id:"cinema",name:"Kino, koncerti, dogodki",dp:0},{id:"social",name:"Družabne aktivnosti (pijače s prijatelji, itd.)",dp:20}]},
  {id:"health",name:"Zdravje",type:"var",subs:[{id:"pharm",name:"Lekarna",dp:0},{id:"massage",name:"Masaža / terapija",dp:0},{id:"suppl",name:"Dodatki k prehrani",dp:0},{id:"dental",name:"Zobozdravstvene storitve",dp:0}]},
  {id:"edu",name:"Izobraževanje",type:"var",subs:[{id:"books",name:"Knjige",dp:0},{id:"courses",name:"Tečaji, delavnice",dp:250}]},
  {id:"subs",name:"Naročnine in članarine",type:"var",subs:[{id:"stream",name:"Storitve pretakanja (Netflix, Spotify, itd.)",dp:0},{id:"members",name:"Članarine (fitnes, košarka)",dp:110},{id:"software",name:"Programska oprema/aplikacije",dp:23}]},
  {id:"gifts",name:"Darila in donacije",type:"var",subs:[{id:"bday",name:"Darila za rojstne dneve, praznike",dp:0},{id:"donate",name:"Donacije dobrodelnim organizacijam",dp:0}]},
  {id:"household",name:"Gospodinjstvo in dom",type:"var",subs:[{id:"repairs",name:"Manjša popravila in vzdrževanje",dp:0},{id:"equip",name:"Oprema za dom",dp:0}]},
  {id:"vacation",name:"Dopust",type:"var",subs:[{id:"travel",name:"Potovanja",dp:0}]},
  {id:"children_var",name:"Otroški stroški (variabilni)",type:"var",subs:[{id:"kidStuff",name:"Igrače, oblačila, plenice, posebna hrana",dp:0},{id:"kidOther",name:"Drugo",dp:0}]},
  {id:"unexpected",name:"Nepredvideni stroški",type:"var",subs:[]},
];
const INCOME_TYPES=["Plača","Nagrada","Regres","Božičnica","Otroški dodatek","Porodniška","Refund"];
const KNOWN_UNX=["Amazon","HM","About You","Sports Direct","Mohito","Notino","Stradivarius","Grand Hotel Bernardin","Best Secret","Equa","Lelosi","DDStepOnline","Fever vstopnice"];
const ALL_SUBS=CATS.flatMap(c=>c.subs);
function fmt(n){return new Intl.NumberFormat("sl-SI",{style:"currency",currency:"EUR",minimumFractionDigits:0,maximumFractionDigits:0}).format(n||0)}
function fN(n){return new Intl.NumberFormat("sl-SI",{minimumFractionDigits:0,maximumFractionDigits:0}).format(n||0)}
function pc(a,b){return b===0?0:Math.round((a/b)*100)}
function initMonth(){const s={};ALL_SUBS.forEach(sub=>{s[sub.id]={plan:sub.dp,actual:0,comment:""}});return{subs:s,income:{Kristina:{},Tadej:{}},customIncome:[],unexpectedItems:[]}}
function initYear(){const y={};for(let i=0;i<12;i++)y[i]=initMonth();return y}
function load(k,fb){try{const s=localStorage.getItem(k);return s?JSON.parse(s):fb}catch{return fb}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function catTotal(md,cat,f){return cat.subs.reduce((s,sub)=>s+(md?.subs?.[sub.id]?.[f]||0),0)}
function fixedTotal(md,f){return CATS.filter(c=>c.type==="fixed").reduce((s,c)=>s+catTotal(md,c,f),0)}
function varTotal(md,f){return CATS.filter(c=>c.type==="var").reduce((s,c)=>s+catTotal(md,c,f),0)}
function incTotal(md){let t=0;Object.values(md?.income?.Kristina||{}).forEach(v=>t+=(v||0));Object.values(md?.income?.Tadej||{}).forEach(v=>t+=(v||0));(md?.customIncome||[]).forEach(ci=>t+=(ci.amount||0));return t}
const C={bg:"#f8f7f4",card:"#fff",brd:"#e8e6e1",mut:"#888",fnt:"#f5f5f0",grn:"#059669",red:"#dc2626",blu:"#2563eb",pur:"#7c3aed",org:"#d97706",txt:"#1a1a2e",sub:"#555"};
const sCard={background:C.card,borderRadius:10,border:`1px solid ${C.brd}`,padding:16,marginBottom:12};
const sMet={background:"#fafaf8",borderRadius:8,padding:"12px 14px",border:"1px solid #eee",marginBottom:4};
const sInp={height:30,fontSize:12,border:"1px solid #ddd",borderRadius:6,padding:"0 8px",outline:"none",boxSizing:"border-box"};
const sSel={height:30,fontSize:12,border:"1px solid #ddd",borderRadius:6,padding:"0 6px",background:"#fff",outline:"none",boxSizing:"border-box"};
const sBtn=p=>({height:30,fontSize:11,fontWeight:600,border:p?"none":"1px solid #ddd",borderRadius:6,padding:"0 14px",background:p?C.blu:"#fff",color:p?"#fff":"#333",cursor:"pointer"});
const sTag=(b,f)=>({fontSize:9,padding:"2px 8px",borderRadius:10,fontWeight:600,background:b,color:f,display:"inline-block"});

function PSlider({label,value,onChange,min,max,step=1,unit=""}){
  return<div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}>
    <span style={{fontSize:11,color:C.mut,minWidth:140}}>{label}</span>
    <input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} style={{flex:1}}/>
    <input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value)||0)} style={{...sInp,width:60,height:26,fontSize:11,textAlign:"right"}}/>
    {unit&&<span style={{fontSize:10,color:C.mut,minWidth:12}}>{unit}</span>}
  </div>
}

// Isolated form components to prevent focus loss
function AddCustomIncome({onAdd}){const[l,sL]=useState('');const[a,sA]=useState('');const[p,sP]=useState('Kristina');const[c,sC]=useState('');return<div style={{display:"flex",gap:4,marginTop:6,alignItems:"center",flexWrap:"wrap"}}><input style={{...sInp,flex:1,minWidth:80,height:26,fontSize:11}} value={l} onChange={e=>sL(e.target.value)} placeholder="Opis"/><input style={{...sInp,width:55,height:26,fontSize:11}} type="number" value={a} onChange={e=>sA(e.target.value)} placeholder="€"/><select style={{...sSel,width:75,height:26,fontSize:11}} value={p} onChange={e=>sP(e.target.value)}><option>Kristina</option><option>Tadej</option></select><input style={{...sInp,flex:0.5,minWidth:50,height:26,fontSize:10}} value={c} onChange={e=>sC(e.target.value)} placeholder="komentar"/><button style={{...sBtn(true),height:26,padding:"0 8px"}} onClick={()=>{if(l){onAdd(l,a,p,c);sL('');sA('');sC('')}}}>+</button></div>}
function AddUnexpected({onAdd}){const[d,sD]=useState('');const[cu,sCu]=useState('');const[a,sA]=useState('');const[p,sP]=useState('Kristina');return<div style={{display:"flex",gap:6,alignItems:"center",marginBottom:8,flexWrap:"wrap"}}><select style={{...sSel,flex:1,minWidth:100}} value={d} onChange={e=>sD(e.target.value)}><option value="">Izberi...</option>{KNOWN_UNX.map(k=><option key={k} value={k}>{k}</option>)}<option value="__c">+ Drugo</option></select>{(d===""||d==="__c")&&<input style={{...sInp,width:80}} value={cu} onChange={e=>sCu(e.target.value)} placeholder="Opis"/>}<input style={{...sInp,width:60}} type="number" value={a} onChange={e=>sA(e.target.value)} placeholder="€"/><select style={{...sSel,width:75}} value={p} onChange={e=>sP(e.target.value)}><option>Kristina</option><option>Tadej</option></select><button style={{...sBtn(true),padding:"0 10px"}} onClick={()=>{const desc=d==="__c"||!d?cu:d;if(desc){onAdd(desc,a,p);sD('');sCu('');sA('')}}}>+</button></div>}
function AddGoalForm({onAdd,onCancel}){const[n,sN]=useState('');const[t,sT]=useState('saving');const[tg,sTg]=useState('');const[src,sSrc]=useState('');const[note,sNote]=useState('');return<div style={{...sCard,border:"1px dashed #93c5fd",background:"#f0f7ff"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}><div><div style={{fontSize:10,color:C.mut,marginBottom:2}}>Ime cilja</div><input style={{...sInp,width:"100%"}} value={n} onChange={e=>sN(e.target.value)} placeholder="npr. Nujni sklad"/></div><div><div style={{fontSize:10,color:C.mut,marginBottom:2}}>Tip</div><select style={{...sSel,width:"100%"}} value={t} onChange={e=>sT(e.target.value)}><option value="saving">Varčevalni</option><option value="limit">Mesečni limit</option><option value="manual">Ročni vnos</option></select></div><div><div style={{fontSize:10,color:C.mut,marginBottom:2}}>Vir podatkov</div><select style={{...sSel,width:"100%"}} value={src} onChange={e=>sSrc(e.target.value)}><option value="">Ročno</option>{ALL_SUBS.map(s=><option key={s.id} value={s.id}>{s.name.substring(0,30)}</option>)}</select></div><div><div style={{fontSize:10,color:C.mut,marginBottom:2}}>Ciljni znesek (€)</div><input style={{...sInp,width:"100%"}} type="number" value={tg} onChange={e=>sTg(e.target.value)} placeholder="0"/></div></div><div style={{marginBottom:8}}><div style={{fontSize:10,color:C.mut,marginBottom:2}}>Opomba</div><input style={{...sInp,width:"100%"}} value={note} onChange={e=>sNote(e.target.value)} placeholder="neobvezno"/></div><div style={{display:"flex",gap:6,justifyContent:"flex-end"}}><button style={sBtn(false)} onClick={onCancel}>Prekliči</button><button style={sBtn(true)} onClick={()=>{if(n&&tg)onAdd({name:n,type:t,target:parseFloat(tg),current:0,source:src,note})}}>Shrani</button></div></div>}

export default function App(){
  const[authState,setAuthState]=useState(()=>sessionStorage.getItem('dp_s')?'auth':'init');
  const[curUser,setCurUser]=useState(()=>sessionStorage.getItem('dp_u')||null);
  const[loginUser,setLoginUser]=useState('');const[loginPass,setLoginPass]=useState('');
  const[setupUser,setSetupUser]=useState('');const[setupPass,setSetupPass]=useState('');const[setupPass2,setSetupPass2]=useState('');
  const[authErr,setAuthErr]=useState('');const[attempts,setAttempts]=useState(0);const[locked,setLocked]=useState(0);const[showForgot,setShowForgot]=useState(false);

  const[view,setView]=useState("dash");const[month,setMonth]=useState(new Date().getMonth());const[dashYear,setDashYear]=useState(2026);
  const[data,setData]=useState(()=>load('dp_data',{2026:initYear()}));
  const[changeLog,setChangeLog]=useState(()=>load('dp_log',[]));
  const[goals,setGoals]=useState(()=>load('dp_goals',[]));
  const[budgetPct,setBudgetPct]=useState(()=>load('dp_pct',{}));
  const[pctMode,setPctMode]=useState(()=>load('dp_pctm',{}));
  const[pctFixed,setPctFixed]=useState(()=>load('dp_pctf',{}));
  const[cryptoUnlocked,setCryptoUnlocked]=useState(false);const[cryptoPwd,setCryptoPwd]=useState("");
  const[cryptoHoldings,setCryptoHoldings]=useState(()=>load('dp_crypto',[{coin:"BTC",amount:0.05,avgPrice:45000},{coin:"ETH",amount:1.2,avgPrice:3200}]));
  const[compareYear,setCompareYear]=useState(null);const[showImport,setShowImport]=useState(false);const[importYear,setImportYear]=useState(2025);
  const[importPreview,setImportPreview]=useState(null);const[importLog,setImportLog]=useState([]);
  const[showNewGoal,setShowNewGoal]=useState(false);const[showSavCfg,setShowSavCfg]=useState(false);
  const[savVis,setSavVis]=useState(()=>load('dp_sv',["vacSav","etf","tradeRep"]));
  const[simFrom,setSimFrom]=useState("2026-05-01");const[simTo,setSimTo]=useState("2029-04-30");
  const[simG,setSimG]=useState(3);const[simI,setSimI]=useState(2);const[simC,setSimC]=useState(5);const[simE,setSimE]=useState(100);
  const[simSc,setSimSc]=useState([]);
  const[sNewPwd,setSNewPwd]=useState('');const[sNewPwd2,setSNewPwd2]=useState('');const[sCryptoPwd,setSCryptoPwd]=useState('');const[sMsg,setSMsg]=useState('');

  useEffect(()=>{save('dp_data',data)},[data]);useEffect(()=>{save('dp_log',changeLog.slice(0,200))},[changeLog]);useEffect(()=>{save('dp_goals',goals)},[goals]);useEffect(()=>{save('dp_crypto',cryptoHoldings)},[cryptoHoldings]);useEffect(()=>{save('dp_pct',budgetPct)},[budgetPct]);useEffect(()=>{save('dp_pctm',pctMode)},[pctMode]);useEffect(()=>{save('dp_pctf',pctFixed)},[pctFixed]);useEffect(()=>{save('dp_sv',savVis)},[savVis]);

  useEffect(()=>{if(authState==='init'){if(sessionStorage.getItem('dp_s')){setAuthState('auth');setCurUser(sessionStorage.getItem('dp_u'))}else setAuthState(localStorage.getItem('dp_accounts')?'login':'setup')}},[]);
  const lastAct=useRef(Date.now());
  useEffect(()=>{if(authState!=='auth')return;const r=()=>{lastAct.current=Date.now()};const c=setInterval(()=>{if(Date.now()-lastAct.current>30*60*1000){setAuthState('login');setCurUser(null);sessionStorage.clear();setAuthErr('Seja potekla.')}},10000);window.addEventListener('mousemove',r);window.addEventListener('keydown',r);return()=>{clearInterval(c);window.removeEventListener('mousemove',r);window.removeEventListener('keydown',r)}},[authState]);

  const doLogin=async()=>{if(locked>Date.now())return;const accs=JSON.parse(localStorage.getItem('dp_accounts')||'[]');const acc=accs.find(a=>a.username===loginUser.trim());if(!acc){failL();return}const h=await hashPwd(loginPass,acc.salt);if(h!==acc.hash){failL();return}setCurUser(acc.username);setAuthState('auth');setAttempts(0);setAuthErr('');sessionStorage.setItem('dp_s','1');sessionStorage.setItem('dp_u',acc.username)};
  const failL=()=>{const n=attempts+1;setAttempts(n);if(n>=5){setLocked(Date.now()+30000);setAuthErr('Preveč poskusov. Počakaj 30s.');setTimeout(()=>{setAttempts(0);setAuthErr('')},30000)}else setAuthErr(`Napačni podatki. ${n}/5.`)};
  const doSetup=async()=>{if(!setupUser.trim()){setAuthErr('Vnesi ime.');return}if(setupPass.length<6){setAuthErr('Geslo ≥ 6 znakov.');return}if(setupPass!==setupPass2){setAuthErr('Gesli se ne ujemata.');return}const salt=crypto.getRandomValues(new Uint8Array(16)).join('');const h=await hashPwd(setupPass,salt);localStorage.setItem('dp_accounts',JSON.stringify([{username:setupUser.trim(),hash:h,salt}]));setCurUser(setupUser.trim());setAuthState('auth');setAuthErr('');sessionStorage.setItem('dp_s','1');sessionStorage.setItem('dp_u',setupUser.trim())};
  const doLogout=()=>{setAuthState('login');setCurUser(null);setLoginPass('');sessionStorage.clear()};
  const doReset=()=>{localStorage.removeItem('dp_accounts');setAuthState('setup');setAuthErr('');setShowForgot(false)};
  const doChgPwd=async()=>{if(sNewPwd.length<6){setSMsg('≥ 6 znakov');return}if(sNewPwd!==sNewPwd2){setSMsg('Gesli se ne ujemata.');return}const accs=JSON.parse(localStorage.getItem('dp_accounts')||'[]');const i=accs.findIndex(a=>a.username===curUser);if(i<0)return;const salt=crypto.getRandomValues(new Uint8Array(16)).join('');accs[i]={...accs[i],hash:await hashPwd(sNewPwd,salt),salt};localStorage.setItem('dp_accounts',JSON.stringify(accs));setSNewPwd('');setSNewPwd2('');setSMsg('Geslo spremenjeno!')};

  const yd=data[dashYear]||initYear();const md=yd[month]||initMonth();
  const tInc=incTotal(md);const tFix=fixedTotal(md,'actual');const tVar=varTotal(md,'actual');const tAct=tFix+tVar;

  const updateSub=(subId,field,val)=>{setData(prev=>{const n=JSON.parse(JSON.stringify(prev));if(!n[dashYear])n[dashYear]=initYear();if(!n[dashYear][month])n[dashYear][month]=initMonth();if(!n[dashYear][month].subs[subId])n[dashYear][month].subs[subId]={plan:0,actual:0,comment:""};const old=n[dashYear][month].subs[subId][field];n[dashYear][month].subs[subId][field]=field==="comment"?val:(parseFloat(val)||0);if(field==="plan"&&parseFloat(val)!==old)setChangeLog(l=>[{date:new Date().toLocaleDateString("sl-SI"),sub:subId,oldVal:old||0,newVal:parseFloat(val)||0,who:curUser||"?"},...l]);return n})};
  const updateInc=(person,type,val)=>{setData(prev=>{const n=JSON.parse(JSON.stringify(prev));if(!n[dashYear])n[dashYear]=initYear();if(!n[dashYear][month])n[dashYear][month]=initMonth();if(!n[dashYear][month].income[person])n[dashYear][month].income[person]={};n[dashYear][month].income[person][type]=parseFloat(val)||0;return n})};
  const addCustInc=(label,amount,person,comment)=>{setData(prev=>{const n=JSON.parse(JSON.stringify(prev));if(!n[dashYear])n[dashYear]=initYear();if(!n[dashYear][month])n[dashYear][month]=initMonth();n[dashYear][month].customIncome.push({label,amount:parseFloat(amount)||0,person,comment});return n})};
  const addUnx=(desc,amount,person)=>{setData(prev=>{const n=JSON.parse(JSON.stringify(prev));if(!n[dashYear])n[dashYear]=initYear();if(!n[dashYear][month])n[dashYear][month]=initMonth();n[dashYear][month].unexpectedItems.push({desc,amount:parseFloat(amount)||0,person});return n})};

  const doExport=()=>{const wb=XLSX.utils.book_new();const ov=[["ODHODKI",...CATS.map(c=>c.name)]];for(let m=0;m<12;m++){const md2=(data[dashYear]||{})[m]||initMonth();ov.push([MS_FULL[m],...CATS.map(c=>catTotal(md2,c,'actual'))])}ov.push([]);ov.push(["PRIHODKI",...INCOME_TYPES]);for(let m=0;m<12;m++){const md2=(data[dashYear]||{})[m]||initMonth();ov.push([MS_FULL[m],...INCOME_TYPES.map(t=>(md2.income?.Kristina?.[t]||0)+(md2.income?.Tadej?.[t]||0))])}XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(ov),"pregled");for(let m=0;m<12;m++){const md2=(data[dashYear]||{})[m]||initMonth();const rows=[["","Izvedba","Plan","Razlika €","","Komentar"],["ODHODKI"]];CATS.forEach(cat=>{rows.push([cat.name+":",catTotal(md2,cat,'actual'),catTotal(md2,cat,'plan')]);cat.subs.forEach(sub=>{const d=md2.subs?.[sub.id]||{plan:0,actual:0,comment:""};rows.push([sub.name,d.actual,d.plan,d.plan-d.actual,"",d.comment])});rows.push([])});rows.push([]);rows.push(["PRIHODKI"]);["Kristina","Tadej"].forEach(p=>{INCOME_TYPES.forEach(t=>{const v=md2.income?.[p]?.[t]||0;if(v>0)rows.push([p,t,v])})});(md2.unexpectedItems||[]).forEach(it=>rows.push([it.desc,it.amount,"","","",it.person]));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),MS_SHORT[m].toLowerCase())}XLSX.writeFile(wb,`proracun_${dashYear}.xlsx`)};

  const handleImportFile=async(e)=>{const file=e.target.files?.[0];if(!file)return;try{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const prev=[];const mm={jan:0,feb:1,mar:2,apr:3,maj:4,jun:5,jul:6,avg:7,sep:8,okt:9,nov:10,dec:11};wb.SheetNames.forEach(sn=>{const snl=sn.toLowerCase().trim();let mi=null;for(const[k,v]of Object.entries(mm)){if(snl.startsWith(k)){mi=v;break}}if(mi===null)return;XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1}).forEach(r=>{if(!r[0]||typeof r[0]!=="string")return;const a=parseFloat(r[1])||0;const p=parseFloat(r[2])||0;if(a>0||p>0)prev.push({month:MS_FULL[mi],mi,label:String(r[0]).trim(),actual:a,plan:p})})});setImportPreview({wb,preview:prev})}catch(err){setImportLog([{type:"err",msg:"Napaka: "+err.message}])}};
  const doImport=()=>{if(!importPreview)return;setData(prev=>{const n=JSON.parse(JSON.stringify(prev));if(!n[importYear])n[importYear]=initYear();importPreview.preview.forEach(r=>{if(!n[importYear][r.mi])n[importYear][r.mi]=initMonth();const lbl=r.label.toLowerCase();CATS.forEach(cat=>{cat.subs.forEach(sub=>{const subL=sub.name.toLowerCase();if(lbl.includes(subL.substring(0,12))||subL.includes(lbl.substring(0,12))){n[importYear][r.mi].subs[sub.id]={plan:r.plan||r.actual,actual:r.actual,comment:""}}})});if(lbl==="kristina"||lbl==="tadej"){const p=lbl==="kristina"?"Kristina":"Tadej";if(!n[importYear][r.mi].income[p])n[importYear][r.mi].income[p]={};n[importYear][r.mi].income[p]["Plača"]=(n[importYear][r.mi].income[p]["Plača"]||0)+r.actual}});return n});setImportPreview(null);setImportLog([{type:"ok",msg:`Uvoženo v ${importYear}!`}])};

  const pieData=CATS.map((c,i)=>({name:c.name.split(" ")[0],value:catTotal(md,c,'actual'),color:COLORS[i%COLORS.length]})).filter(d=>d.value>0);
  const trendData=MS_SHORT.map((m,i)=>{const mdata=yd[i]||initMonth();return{name:m,Prihodki:incTotal(mdata),Odhodki:fixedTotal(mdata,'actual')+varTotal(mdata,'actual')}});
  const simData=(()=>{const sY=parseInt(simFrom.split("-")[0])||2026;const eY=parseInt(simTo.split("-")[0])||2029;const yrs=Math.max(1,eY-sY+1);const mI=tInc||3600;const mE=tAct||3100;const mS=catTotal(md,CATS.find(c=>c.id==="savings")||{subs:[]},'actual')||500;const r=[];for(let i=0;i<yrs;i++){const ig=Math.pow(1+simG/100,i);const eg=Math.pow(1+simI/100,i);let yI=Math.round(mI*ig*12);let yE=Math.round(mE*eg*12);const yS=Math.round((mS+simE)*ig*12);const cum=r.length>0?r[r.length-1].Prihranki+yS:yS;simSc.forEach(sc=>{const yr=sY+i;if(sc.type==="mortgage"&&yr>=sc.year)yE+=sc.amount*12;if(sc.type==="raise"&&yr>=sc.year)yI=Math.round(yI*(1+sc.pct/100));if(sc.type==="jobLoss"&&yr===sc.year)yI=Math.round(yI*0.4);if(sc.type==="move"&&yr>=sc.year)yE+=sc.amount*12});r.push({name:String(sY+i),Prihodki:yI,Odhodki:yE,Prihranki:cum})}return r})();

  const navP=()=>{if(month===0){setMonth(11);setDashYear(y=>y-1)}else setMonth(m=>m-1)};
  const navN=()=>{if(month===11){setMonth(0);setDashYear(y=>y+1)}else setMonth(m=>m+1)};

  const aCard={background:'#fff',borderRadius:16,padding:'2.5rem',width:360,boxShadow:'0 2px 24px rgba(0,0,0,0.06)',border:'1px solid #e8e6e1'};
  const aPage={minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',background:'#f8f7f4',fontFamily:"'Segoe UI',system-ui,sans-serif"};
  const aInp={width:'100%',height:40,fontSize:14,border:'1px solid #ddd',borderRadius:8,padding:'0 12px',outline:'none',boxSizing:'border-box',marginBottom:12};
  const aBtn={width:'100%',height:42,fontSize:14,fontWeight:600,border:'none',borderRadius:8,background:'#2563eb',color:'#fff',cursor:'pointer',marginTop:8};

  if(authState==='init')return<div style={aPage}><div style={aCard}><p>Nalagam...</p></div></div>;
  if(authState==='setup')return<div style={aPage}><div style={aCard}><div style={{fontSize:32,textAlign:'center',marginBottom:8}}>💰</div><h2 style={{textAlign:'center',margin:'0 0 20px'}}>Ustvari račun</h2><input style={aInp} value={setupUser} onChange={e=>setSetupUser(e.target.value)} placeholder="Uporabniško ime"/><input style={aInp} type="password" value={setupPass} onChange={e=>setSetupPass(e.target.value)} placeholder="Geslo (≥ 6 znakov)"/><input style={aInp} type="password" value={setupPass2} onChange={e=>setSetupPass2(e.target.value)} placeholder="Ponovi geslo" onKeyDown={e=>{if(e.key==='Enter')doSetup()}}/><button style={aBtn} onClick={doSetup}>Ustvari</button>{authErr&&<div style={{fontSize:12,color:C.red,textAlign:'center',marginTop:8}}>{authErr}</div>}</div></div>;
  if(authState==='login')return<div style={aPage}><div style={aCard}><div style={{fontSize:32,textAlign:'center',marginBottom:8}}>🔐</div><h2 style={{textAlign:'center',margin:'0 0 20px'}}>Prijava</h2><input style={aInp} value={loginUser} onChange={e=>setLoginUser(e.target.value)} placeholder="Uporabniško ime" disabled={locked>Date.now()}/><input style={aInp} type="password" value={loginPass} onChange={e=>setLoginPass(e.target.value)} placeholder="Geslo" disabled={locked>Date.now()} onKeyDown={e=>{if(e.key==='Enter')doLogin()}}/><button style={{...aBtn,opacity:locked>Date.now()?0.5:1}} onClick={doLogin} disabled={locked>Date.now()}>Prijava</button>{authErr&&<div style={{fontSize:12,color:C.red,textAlign:'center',marginTop:8}}>{authErr}</div>}<div style={{textAlign:'center',marginTop:12}}>{!showForgot?<button onClick={()=>setShowForgot(true)} style={{background:'none',border:'none',color:C.blu,fontSize:12,cursor:'pointer',textDecoration:'underline'}}>Pozabljeno geslo?</button>:<div style={{background:'#fef3c7',padding:10,borderRadius:8,fontSize:11,color:'#92400e',marginTop:8}}><p style={{margin:'0 0 6px',fontWeight:600}}>Ponastavitev</p><p style={{margin:'0 0 8px'}}>To izbriše račune (podatki ostanejo).</p><button onClick={doReset} style={{...sBtn(false),color:C.red,borderColor:C.red,fontSize:11,height:26}}>Ponastavi</button> <button onClick={()=>setShowForgot(false)} style={{...sBtn(false),fontSize:11,height:26}}>Prekliči</button></div>}</div></div></div>;

  // AUTHENTICATED
  const MNav=<div style={{display:"flex",alignItems:"center",gap:6}}><button onClick={navP} style={sBtn(false)}>←</button><span style={{fontSize:14,fontWeight:600,minWidth:120,textAlign:"center"}}>{MS_FULL[month]} {dashYear}</span><button onClick={navN} style={sBtn(false)}>→</button></div>;
  const YPick=<div style={{display:"flex",alignItems:"center",gap:4,flexWrap:"wrap"}}><span style={{fontSize:10,color:C.mut}}>Leto:</span><select style={{...sSel,height:26,fontSize:11,width:70}} value={dashYear} onChange={e=>setDashYear(parseInt(e.target.value))}>{[2020,2021,2022,2023,2024,2025,2026,2027,2028].map(y=><option key={y} value={y}>{y}</option>)}</select><span style={{fontSize:10,color:C.mut,marginLeft:4}}>vs:</span><select style={{...sSel,height:26,fontSize:11,width:70}} value={compareYear||""} onChange={e=>setCompareYear(e.target.value?parseInt(e.target.value):null)}><option value="">—</option>{[2020,2021,2022,2023,2024,2025,2026,2027].filter(y=>y!==dashYear).map(y=><option key={y} value={y}>{y}</option>)}</select></div>;

  return<ErrorBoundary><div style={{fontFamily:"'Segoe UI',system-ui,sans-serif",color:C.txt,minHeight:"100vh",background:C.bg}}>
    <div style={{position:'fixed',top:0,right:0,zIndex:100,padding:'5px 12px',display:'flex',alignItems:'center',gap:6,fontSize:11,color:'#888',background:'rgba(248,247,244,0.95)',borderBottomLeftRadius:6,border:'1px solid #e8e6e1',borderTop:'none',borderRight:'none'}}><span style={{fontWeight:500,color:C.blu}}>{curUser}</span><button onClick={doLogout} style={{fontSize:10,padding:'2px 8px',border:'1px solid #ddd',borderRadius:4,background:'#fff',cursor:'pointer'}}>Odjava</button></div>
    <div style={{display:"flex",gap:0,background:C.txt,padding:"0 8px",overflowX:"auto"}}>{[["dash","Nadzorna plošča"],["entry","Mesečni vnos"],["annual","Letni pregled"],["goals","Cilji"],["sim","Simulacija"],["pct","% razdelitev"],["settings","Nastavitve"],["crypto","🔒"]].map(([k,l])=><div key={k} style={{padding:"10px 12px",fontSize:12,fontWeight:view===k?600:400,color:view===k?"#f8f7f4":"#8888a0",cursor:"pointer",borderBottom:view===k?"2px solid #60a5fa":"2px solid transparent",whiteSpace:"nowrap"}} onClick={()=>setView(k)}>{l}</div>)}</div>
    <div style={{padding:"1.25rem 1.25rem 2rem"}}>

    {view==="dash"&&<div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8,flexWrap:"wrap",gap:8}}><h2 style={{fontSize:20,fontWeight:700,margin:0}}>Nadzorna plošča</h2><div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>{YPick}<button onClick={()=>setShowImport(!showImport)} style={{...sBtn(false),fontSize:10}}>Uvoz</button><button onClick={doExport} style={{...sBtn(false),fontSize:10}}>Izvoz</button>{MNav}</div></div>
      {showImport&&<div style={{...sCard,background:"#f0f7ff",border:"1px dashed #93c5fd"}}><div style={{fontSize:12,fontWeight:600,color:C.blu,marginBottom:4}}>Uvozi iz Excel</div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:8,flexWrap:"wrap"}}><span style={{fontSize:11}}>V leto:</span><select style={{...sSel,width:70}} value={importYear} onChange={e=>setImportYear(parseInt(e.target.value))}>{[2020,2021,2022,2023,2024,2025,2026,2027,2028].map(y=><option key={y} value={y}>{y}</option>)}</select><input type="file" accept=".xlsx,.xls" onChange={handleImportFile} style={{fontSize:12}}/></div>{importPreview&&<div style={{border:"1px solid #e8e6e1",borderRadius:6,padding:8,background:"#fff",maxHeight:180,overflowY:"auto",marginBottom:8}}><div style={{fontSize:11,fontWeight:600,marginBottom:4}}>Predogled ({importPreview.preview.length} vnosov → {importYear}):</div><table style={{width:"100%",fontSize:10,borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left",padding:2}}>Mesec</th><th style={{textAlign:"left",padding:2}}>Postavka</th><th style={{textAlign:"right",padding:2}}>Izvedba</th><th style={{textAlign:"right",padding:2}}>Plan</th></tr></thead><tbody>{importPreview.preview.slice(0,25).map((r,i)=><tr key={i}><td style={{padding:2}}>{r.month}</td><td style={{padding:2}}>{r.label.substring(0,28)}</td><td style={{textAlign:"right",padding:2}}>{r.actual>0?fmt(r.actual):"—"}</td><td style={{textAlign:"right",padding:2}}>{r.plan>0?fmt(r.plan):"—"}</td></tr>)}</tbody></table><div style={{display:"flex",gap:6,marginTop:8}}><button style={sBtn(true)} onClick={doImport}>Potrdi uvoz</button><button style={sBtn(false)} onClick={()=>setImportPreview(null)}>Prekliči</button></div></div>}{importLog.map((l,i)=><div key={i} style={{fontSize:11,color:l.type==="ok"?C.grn:C.red}}>{l.msg}</div>)}</div>}
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:14}}>
        <div style={sMet}><div style={{fontSize:10,color:C.mut,textTransform:"uppercase"}}>Prihodki</div><div style={{fontSize:20,fontWeight:600,color:C.grn}}>{fmt(tInc)}</div></div>
        <div style={sMet}><div style={{fontSize:10,color:C.mut,textTransform:"uppercase"}}>Odhodki</div><div style={{fontSize:20,fontWeight:600,color:C.red}}>{fmt(tAct)}</div><div style={{fontSize:10,color:"#999"}}>F {fmt(tFix)} + V {fmt(tVar)}</div></div>
        <div style={sMet}><div style={{fontSize:10,color:C.mut,textTransform:"uppercase"}}>Razlika</div><div style={{fontSize:20,fontWeight:600,color:tInc-tAct>=0?C.grn:C.red}}>{tInc-tAct>=0?"+":""}{fmt(tInc-tAct)}</div></div>
        <div style={{...sMet,position:"relative"}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:10,color:C.mut,textTransform:"uppercase"}}>Varčevanje</span><span onClick={()=>setShowSavCfg(!showSavCfg)} style={{...sTag("#dbeafe",C.blu),fontSize:8,cursor:"pointer"}}>⚙</span></div><div style={{fontSize:20,fontWeight:600,color:C.blu}}>{fmt(savVis.reduce((s,id)=>s+(md.subs?.[id]?.actual||0),0))}</div>{showSavCfg&&<div style={{position:"absolute",top:"100%",right:0,zIndex:20,background:"#fff",border:`1px solid ${C.brd}`,borderRadius:8,padding:10,minWidth:200,boxShadow:"0 4px 16px rgba(0,0,0,0.12)"}}>{CATS.find(c=>c.id==="savings").subs.map(s=><label key={s.id} style={{display:"flex",alignItems:"center",gap:6,fontSize:11,padding:"2px 0",cursor:"pointer"}}><input type="checkbox" checked={savVis.includes(s.id)} onChange={e=>{if(e.target.checked)setSavVis(v=>[...v,s.id]);else setSavVis(v=>v.filter(x=>x!==s.id))}}/>{s.name.substring(0,25)}</label>)}<button onClick={()=>setShowSavCfg(false)} style={{...sBtn(true),height:22,fontSize:10,marginTop:4,width:"100%"}}>OK</button></div>}</div>
      </div>
      <div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Plan po kategorijah</div>
      <div style={sCard}>{CATS.map(cat=>{const pT=catTotal(md,cat,'plan');const aT=catTotal(md,cat,'actual');const p=pc(aT,pT);return<div key={cat.id} style={{display:"flex",alignItems:"center",gap:6,padding:"4px 0",borderBottom:`1px solid ${C.fnt}`,fontSize:11}}><span style={{flex:1,fontWeight:500}}>{cat.name.length>22?cat.name.substring(0,20)+"…":cat.name}</span><span style={{color:"#999",minWidth:50,textAlign:"right"}}>{fmt(pT)}</span><span style={{minWidth:50,textAlign:"right"}}>{fmt(aT)}</span><span style={{minWidth:28,textAlign:"right",fontWeight:600,color:p>90?C.red:p>70?C.org:C.grn}}>{pT>0?p+"%":"—"}</span><div style={{width:50,height:4,borderRadius:2,background:"#eee",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(p,100)}%`,borderRadius:2,background:p>90?C.red:p>70?C.org:C.grn}}/></div></div>})}</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
        <div style={sCard}><div style={{fontSize:12,fontWeight:600,color:C.sub,marginBottom:6}}>Razdelitev</div>{pieData.length>0?<div style={{display:"flex",alignItems:"center",gap:10}}><ResponsiveContainer width={110} height={110}><PieChart><Pie data={pieData} innerRadius={26} outerRadius={50} dataKey="value" stroke="none">{pieData.map((d,i)=><Cell key={i} fill={d.color}/>)}</Pie></PieChart></ResponsiveContainer><div style={{fontSize:10,color:"#666"}}>{pieData.slice(0,6).map((d,i)=><div key={i}><span style={{display:"inline-block",width:8,height:8,borderRadius:2,background:d.color,marginRight:3}}/>{d.name} {pc(d.value,tAct)}%</div>)}</div></div>:<div style={{fontSize:11,color:"#999",textAlign:"center",padding:16}}>Vnesi podatke</div>}</div>
        <div style={sCard}><div style={{fontSize:12,fontWeight:600,color:C.sub,marginBottom:6}}>Trend {dashYear}</div><ResponsiveContainer width="100%" height={110}><BarChart data={trendData} barGap={1}><XAxis dataKey="name" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>fmt(v)} contentStyle={{fontSize:11}}/><Bar dataKey="Prihodki" fill={C.grn} radius={[2,2,0,0]} barSize={7}/><Bar dataKey="Odhodki" fill={C.red} radius={[2,2,0,0]} barSize={7} opacity={0.6}/></BarChart></ResponsiveContainer></div>
      </div>
    </div>}

    {view==="entry"&&<div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12,flexWrap:"wrap",gap:8}}><h2 style={{fontSize:20,fontWeight:700,margin:0}}>Mesečni vnos</h2><div style={{display:"flex",gap:8,alignItems:"center"}}>{YPick}{MNav}</div></div>
      <div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Prihodki</div>
      <div style={sCard}>{["Kristina","Tadej"].map(person=><div key={person} style={{marginBottom:8}}><div style={{fontSize:12,fontWeight:600,color:C.blu,marginBottom:4}}>{person}</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{INCOME_TYPES.map(t=><div key={`${person}-${t}`}><div style={{fontSize:9,color:"#999"}}>{t}</div><input style={{...sInp,height:26,fontSize:11,width:"100%"}} defaultValue={md.income?.[person]?.[t]||""} onBlur={e=>updateInc(person,t,e.target.value)} placeholder="0"/></div>)}</div></div>)}<div style={{borderTop:`1px solid ${C.brd}`,paddingTop:8}}><div style={{fontSize:11,fontWeight:600,color:C.sub,marginBottom:4}}>Dodatni prihodki</div>{(md.customIncome||[]).map((ci,i)=><div key={i} style={{fontSize:11,padding:"2px 0"}}>{ci.label} — {ci.person} — {fmt(ci.amount)}</div>)}<AddCustomIncome onAdd={addCustInc}/></div></div>
      {[{title:"Fiksni stroški",cats:CATS.filter(c=>c.type==="fixed")},{title:"Variabilni stroški",cats:CATS.filter(c=>c.type==="var"&&c.id!=="unexpected")}].map(sec=><div key={sec.title}><div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>{sec.title}</div><div style={sCard}><div style={{display:"grid",gridTemplateColumns:"1.6fr 60px 60px 50px 1fr",gap:4,fontSize:10,color:C.mut,fontWeight:600,padding:"0 0 6px",borderBottom:"1px solid #eee"}}><span>Postavka</span><span>Plan</span><span>Izvedba</span><span>Razl.</span><span>Komentar</span></div>{sec.cats.map(cat=><React.Fragment key={cat.id}><div style={{fontSize:12,fontWeight:600,color:C.txt,padding:"8px 0 2px",borderTop:`1px solid ${C.brd}`}}>{cat.name}</div>{cat.subs.map(sub=>{const d=md.subs?.[sub.id]||{plan:0,actual:0,comment:""};const diff=d.plan-d.actual;return<div key={sub.id} style={{display:"grid",gridTemplateColumns:"1.6fr 60px 60px 50px 1fr",gap:4,fontSize:11,alignItems:"center",padding:"3px 0",borderBottom:`1px solid ${C.fnt}`}}><span style={{fontSize:10}}>{sub.name.length>32?sub.name.substring(0,30)+"…":sub.name}</span><span style={{color:"#999",fontSize:10}}>{fN(d.plan)}</span><input style={{...sInp,width:55,height:26,fontSize:11}} defaultValue={d.actual||""} onBlur={e=>updateSub(sub.id,"actual",e.target.value)} placeholder="0"/><span style={{fontSize:10,color:diff>=0?C.grn:C.red}}>{diff>=0?"+":""}{fN(diff)}</span><input style={{...sInp,height:26,fontSize:10}} defaultValue={d.comment} onBlur={e=>updateSub(sub.id,"comment",e.target.value)} placeholder=""/></div>})}</React.Fragment>)}</div></div>)}
      <div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Nepredvideni stroški</div>
      <div style={sCard}><AddUnexpected onAdd={addUnx}/>{(md.unexpectedItems||[]).map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",fontSize:11,padding:"2px 0",borderBottom:`1px solid ${C.fnt}`}}><span>{it.desc}</span><span>{fmt(it.amount)} ({it.person})</span></div>)}</div>
      <div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Hitro dodaj cilj</div>
      {showNewGoal?<AddGoalForm onAdd={g=>{setGoals(p=>[...p,{id:Date.now(),...g}]);setShowNewGoal(false)}} onCancel={()=>setShowNewGoal(false)}/>:<button style={{...sBtn(false),fontSize:11}} onClick={()=>setShowNewGoal(true)}>+ Nov cilj</button>}
    </div>}

    {view==="annual"&&<div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12,flexWrap:"wrap",gap:8}}><h2 style={{fontSize:20,fontWeight:700,margin:0}}>Letni pregled</h2>{YPick}</div>
      <div style={{...sCard,overflowX:"auto"}}><table style={{width:"100%",fontSize:10,borderCollapse:"collapse"}}><thead><tr style={{color:C.mut}}><th style={{textAlign:"left",padding:"3px 6px"}}>Kategorija</th>{MS_SHORT.map(m=><th key={m} style={{textAlign:"right",padding:"3px 4px"}}>{m}</th>)}<th style={{textAlign:"right",padding:"3px 6px",fontWeight:700}}>Skupaj</th></tr></thead><tbody>{CATS.map(cat=>{let tot=0;return<tr key={cat.id} style={{borderTop:`1px solid ${C.fnt}`}}><td style={{padding:"3px 6px",fontWeight:500,maxWidth:100,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{cat.name}</td>{Array.from({length:12},(_,i)=>{const mdata=yd[i]||initMonth();const v=catTotal(mdata,cat,'actual');tot+=v;return<td key={i} style={{textAlign:"right",padding:"3px 4px",color:v>0?"#333":"#ccc"}}>{v>0?fN(v):"—"}</td>})}<td style={{textAlign:"right",padding:"3px 6px",fontWeight:700}}>{tot>0?fmt(tot):"—"}</td></tr>})}</tbody></table></div>
      <div style={sCard}><ResponsiveContainer width="100%" height={160}><LineChart data={trendData}><XAxis dataKey="name" tick={{fontSize:10}} axisLine={false}/><YAxis tick={{fontSize:10}} axisLine={false}/><Tooltip formatter={v=>fmt(v)} contentStyle={{fontSize:11}}/><Legend wrapperStyle={{fontSize:10}}/><Line type="monotone" dataKey="Prihodki" stroke={C.grn} strokeWidth={2} dot={{r:3}}/><Line type="monotone" dataKey="Odhodki" stroke={C.red} strokeWidth={2} dot={{r:3}}/></LineChart></ResponsiveContainer></div>
    </div>}

    {view==="goals"&&<div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h2 style={{fontSize:20,fontWeight:700,margin:0}}>Proračunski cilji</h2><button style={sBtn(true)} onClick={()=>setShowNewGoal(!showNewGoal)}>+ Nov cilj</button></div>
      {showNewGoal&&<AddGoalForm onAdd={g=>{setGoals(p=>[...p,{id:Date.now(),...g}]);setShowNewGoal(false)}} onCancel={()=>setShowNewGoal(false)}/>}
      {goals.map(g=>{const p=g.target>0?pc(g.current||0,g.target):0;return<div key={g.id} style={sCard}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}><span style={{fontSize:14,fontWeight:600}}>{g.name}</span><div style={{display:"flex",gap:4,alignItems:"center"}}><span style={sTag(g.type==="saving"?"#dbeafe":"#fef3c7",g.type==="saving"?C.blu:"#92400e")}>{g.type}</span><button onClick={()=>setGoals(prev=>prev.filter(x=>x.id!==g.id))} style={{fontSize:9,color:C.red,background:"none",border:"none",cursor:"pointer"}}>✕</button></div></div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:4}}><span style={{fontSize:11,color:C.mut}}>Trenutno:</span><input style={{...sInp,width:80,height:26,fontSize:11}} defaultValue={g.current||0} onBlur={e=>setGoals(prev=>prev.map(x=>x.id===g.id?{...x,current:parseFloat(e.target.value)||0}:x))}/><span style={{fontSize:11,color:C.mut}}>/ {fmt(g.target)}</span>{g.source&&<span style={{fontSize:10,color:C.blu}}>← {ALL_SUBS.find(s=>s.id===g.source)?.name?.substring(0,20)||g.source}</span>}</div><div style={{height:5,borderRadius:3,background:"#eee",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(p,100)}%`,borderRadius:3,background:p>90&&g.type==="limit"?C.red:C.blu}}/></div><div style={{fontSize:10,color:C.mut,marginTop:4}}>{p}% {g.note&&`— ${g.note}`}</div></div>})}
    </div>}

    {view==="sim"&&<div>
      <h2 style={{fontSize:20,fontWeight:700,margin:"0 0 12px"}}>Finančna simulacija</h2>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Časovni okvir</div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:8,flexWrap:"wrap"}}><span style={{fontSize:11,color:C.mut}}>Od:</span><input type="date" style={{...sInp,width:140}} value={simFrom} onChange={e=>setSimFrom(e.target.value)}/><span style={{fontSize:11,color:C.mut}}>Do:</span><input type="date" style={{...sInp,width:140}} value={simTo} onChange={e=>setSimTo(e.target.value)}/></div><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{[["1 leto","2027-04-30"],["3 leta","2029-04-30"],["5 let","2031-04-30"],["10 let","2036-04-30"]].map(([l,d])=><button key={l} style={sBtn(simTo===d)} onClick={()=>setSimTo(d)}>{l}</button>)}</div></div>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Predpostavke</div><PSlider label="Rast plač (%/leto)" value={simG} onChange={setSimG} min={-15} max={15} unit="%"/><PSlider label="Inflacija (%/leto)" value={simI} onChange={setSimI} min={-10} max={10} unit="%"/><PSlider label="Rast str. vrtca (%)" value={simC} onChange={setSimC} min={-10} max={15} unit="%"/><PSlider label="Dod. naložbe/mesec" value={simE} onChange={setSimE} min={-500} max={500} step={10} unit="€"/></div>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Scenariji</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button style={sBtn(false)} onClick={()=>setSimSc(s=>[...s,{type:"mortgage",year:2027,amount:800}])}>+ Hipoteka 2027</button><button style={sBtn(false)} onClick={()=>setSimSc(s=>[...s,{type:"raise",year:2027,pct:10}])}>+ Povišica 10%</button><button style={sBtn(false)} onClick={()=>setSimSc(s=>[...s,{type:"jobLoss",year:2028}])}>+ Izguba službe</button><button style={sBtn(false)} onClick={()=>setSimSc(s=>[...s,{type:"move",year:2027,amount:-200}])}>+ Cenejše stanovanje</button>{simSc.length>0&&<button style={{...sBtn(false),color:C.red,borderColor:C.red}} onClick={()=>setSimSc([])}>Počisti</button>}</div>{simSc.length>0&&<div style={{marginTop:6,fontSize:10,color:C.blu}}>Aktivni: {simSc.map(s=>s.type).join(", ")}</div>}</div>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,color:C.sub,marginBottom:8}}>Projekcija</div><ResponsiveContainer width="100%" height={200}><BarChart data={simData} barGap={2}><XAxis dataKey="name" tick={{fontSize:10}} axisLine={false}/><YAxis tick={{fontSize:9}} axisLine={false} tickFormatter={v=>`€${Math.round(v/1000)}k`}/><Tooltip formatter={v=>fmt(v)} contentStyle={{fontSize:11}}/><Legend wrapperStyle={{fontSize:10}}/><Bar dataKey="Prihodki" fill={C.grn} radius={[3,3,0,0]} barSize={14}/><Bar dataKey="Odhodki" fill={C.red} radius={[3,3,0,0]} barSize={14} opacity={0.6}/><Bar dataKey="Prihranki" fill={C.blu} radius={[3,3,0,0]} barSize={14} opacity={0.8}/></BarChart></ResponsiveContainer></div>
    </div>}

    {view==="pct"&&<div>
      <h2 style={{fontSize:20,fontWeight:700,margin:"0 0 6px"}}>% razdelitev</h2>
      <div style={{fontSize:11,color:C.mut,marginBottom:12}}>Nastavi % ali fiksni € znesek. Ni sinhronizirano z mesečnim vnosom.</div>
      <div style={sCard}>{CATS.map(cat=>{const mode=pctMode[cat.id]||"pct";const pV=budgetPct[cat.id]||0;const fV=pctFixed[cat.id]||0;const base=tInc||3600;const target=mode==="pct"?Math.round(base*pV/100):fV;return<div key={cat.id} style={{display:"flex",alignItems:"center",gap:6,padding:"4px 0",borderBottom:`1px solid ${C.fnt}`,fontSize:11}}><span style={{minWidth:110,fontWeight:500}}>{cat.name.length>16?cat.name.substring(0,14)+"…":cat.name}</span><select style={{...sSel,width:40,height:24,fontSize:10}} value={mode} onChange={e=>setPctMode(p=>({...p,[cat.id]:e.target.value}))}><option value="pct">%</option><option value="fixed">€</option></select>{mode==="pct"?<><input type="range" min={0} max={50} value={pV} onChange={e=>setBudgetPct(p=>({...p,[cat.id]:parseInt(e.target.value)}))} style={{flex:1}}/><input type="number" min={0} max={100} value={pV} onChange={e=>setBudgetPct(p=>({...p,[cat.id]:parseInt(e.target.value)||0}))} style={{...sInp,width:40,height:24,fontSize:10,textAlign:"right"}}/><span style={{fontSize:10,color:C.mut}}>%</span></>:<><input type="number" value={fV} onChange={e=>setPctFixed(p=>({...p,[cat.id]:parseInt(e.target.value)||0}))} style={{...sInp,flex:1,height:24,fontSize:11}}/><span style={{fontSize:10,color:C.mut}}>€</span></>}<span style={{minWidth:50,textAlign:"right",fontWeight:600}}>{fmt(target)}</span></div>})}<div style={{marginTop:10,padding:"8px 0 0",borderTop:`2px solid ${C.brd}`}}><span style={{fontSize:12,fontWeight:700}}>Skupaj: {fmt(CATS.reduce((s,cat)=>{const m=pctMode[cat.id]||"pct";return s+(m==="pct"?Math.round((tInc||3600)*(budgetPct[cat.id]||0)/100):(pctFixed[cat.id]||0))},0))}</span></div></div>
    </div>}

    {view==="settings"&&<div>
      <h2 style={{fontSize:20,fontWeight:700,margin:"0 0 12px"}}>Nastavitve</h2>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,marginBottom:6}}>Uporabnik</div><div style={{fontSize:12}}>Prijavljen: <strong>{curUser}</strong></div></div>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,marginBottom:6}}>Spremeni geslo</div><input style={{...sInp,width:"100%",marginBottom:6}} type="password" value={sNewPwd} onChange={e=>setSNewPwd(e.target.value)} placeholder="Novo geslo (≥ 6)"/><input style={{...sInp,width:"100%",marginBottom:6}} type="password" value={sNewPwd2} onChange={e=>setSNewPwd2(e.target.value)} placeholder="Ponovi"/><button style={sBtn(true)} onClick={doChgPwd}>Spremeni</button></div>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,marginBottom:6}}>Kripto geslo</div><input style={{...sInp,width:"100%",marginBottom:6}} type="password" value={sCryptoPwd} onChange={e=>setSCryptoPwd(e.target.value)} placeholder="Geslo za kripto sekcijo"/><button style={sBtn(true)} onClick={()=>{save('dp_cpwd',sCryptoPwd);setSMsg('Kripto geslo nastavljeno!');setSCryptoPwd('')}}>Nastavi</button></div>
      <div style={sCard}><div style={{fontSize:13,fontWeight:600,marginBottom:6}}>Podatki</div><button style={{...sBtn(false),marginRight:8}} onClick={doExport}>Izvoz Excel</button><button style={{...sBtn(false),color:C.red,borderColor:C.red}} onClick={()=>{if(confirm('Izbriši vse?')){localStorage.clear();sessionStorage.clear();window.location.reload()}}}>Izbriši vse</button></div>
      {sMsg&&<div style={{fontSize:12,color:C.grn,marginTop:8}}>{sMsg}</div>}
    </div>}

    {view==="crypto"&&<div>
      {!cryptoUnlocked?<div style={{...sCard,display:"flex",flexDirection:"column",alignItems:"center",padding:"3rem",textAlign:"center"}}><div style={{fontSize:40,marginBottom:12}}>🔒</div><div style={{fontSize:16,fontWeight:700,marginBottom:12}}>Kripto sekcija</div><div style={{display:"flex",gap:6}}><input type="password" style={{...sInp,width:160}} value={cryptoPwd} onChange={e=>setCryptoPwd(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){const s=load('dp_cpwd','');if(!s||cryptoPwd===s)setCryptoUnlocked(true)}}} placeholder="Geslo"/><button style={sBtn(true)} onClick={()=>{const s=load('dp_cpwd','');if(!s||cryptoPwd===s)setCryptoUnlocked(true)}}>Odkleni</button></div></div>
      :<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h2 style={{fontSize:20,fontWeight:700,margin:0}}>Kripto</h2><button style={{...sBtn(false),fontSize:10}} onClick={()=>{setCryptoUnlocked(false);setCryptoPwd("")}}>🔒</button></div>
        <div style={sCard}><table style={{width:"100%",fontSize:12,borderCollapse:"collapse"}}><thead><tr style={{color:C.mut}}><th style={{textAlign:"left",padding:6}}>Kovanec</th><th style={{textAlign:"right",padding:6}}>Količina</th><th style={{textAlign:"right",padding:6}}>Cena</th><th style={{textAlign:"right",padding:6}}>Vrednost</th></tr></thead><tbody>{cryptoHoldings.map((h,i)=><tr key={i} style={{borderBottom:`1px solid ${C.fnt}`}}><td style={{padding:6}}><input style={{...sInp,width:55,fontWeight:600}} defaultValue={h.coin} onBlur={e=>{const n=[...cryptoHoldings];n[i]={...n[i],coin:e.target.value};setCryptoHoldings(n)}}/></td><td style={{textAlign:"right",padding:6}}><input type="number" step="0.01" style={{...sInp,width:75,textAlign:"right"}} defaultValue={h.amount} onBlur={e=>{const n=[...cryptoHoldings];n[i]={...n[i],amount:parseFloat(e.target.value)||0};setCryptoHoldings(n)}}/></td><td style={{textAlign:"right",padding:6}}><input type="number" style={{...sInp,width:75,textAlign:"right"}} defaultValue={h.avgPrice} onBlur={e=>{const n=[...cryptoHoldings];n[i]={...n[i],avgPrice:parseFloat(e.target.value)||0};setCryptoHoldings(n)}}/></td><td style={{textAlign:"right",padding:6,fontWeight:600}}>{fmt(Math.round(h.amount*h.avgPrice))}</td></tr>)}</tbody></table><button style={{...sBtn(false),marginTop:8,fontSize:10}} onClick={()=>setCryptoHoldings(h=>[...h,{coin:"",amount:0,avgPrice:0}])}>+ Dodaj</button></div>
        <div style={sMet}><div style={{fontSize:10,color:C.mut,textTransform:"uppercase"}}>Skupaj</div><div style={{fontSize:20,fontWeight:600,color:C.pur}}>{fmt(cryptoHoldings.reduce((s,h)=>s+Math.round(h.amount*h.avgPrice),0))}</div></div>
      </div>}
    </div>}

    </div></div></ErrorBoundary>;
}
